name: "barrelman"
version: "0.0.1"
usage: "A deployment tool that functions independently and as a Helm plugin"
description: |-
  This plugin allows complex values overrides for grouped Helm charts.
ignoreFlags: false
useTunnel: false
flags: "install deploy Barrelman manifest"
command: "$HELM_PLUGIN_DIR/barrelman"