name: "barrelman"
version: "0.0.1"
usage: "barrelman compatible deployment tool"
description: |-
  This plugin deploys barrelman format manifests
ignoreFlags: false
useTunnel: false
flags: "install deploy barrelman manifest"
command: "$HELM_PLUGIN_DIR/barrelman"