---
$id: ./docs/schemas/v0/barrelman/config.yaml
description: The Barrelman configuration yaml defines the desired infrastructure and control plane for a Flagship cluster.
type: object
additionalProperties: false
properties:
  schema:
    description: The API of the schema.
    type: string
  name:
    description: The name of the manifest.
    type: string
  releaseName:
    type: string
  namespace:
    description: The namespace for the manifest to be deployed in.
    type: string
  parallel:
    description: A boolean that sets whether or not the chart groups in the given manifest are to be deployed in parallel.
    type: boolean
  chartGroups:
    description: The list of the chart groups deployed in the manifest.
    type: array
    items:
      type: object
      schema:
        type: string
      name:
        type: string
      namespace:
        description: The namespace for the chart group to be deployed in.
        type: string
      parallel:
        description: A boolean that sets whether or not the charts in the given chart group are to be deployed in parallel.
        type: boolean
      charts:
        type: array
        items:
        - schema:
            type: string
          name:
            type: string
          namespace:
            description: The namespace for the chart to be deployed in.
            type: string
          values:
            type: object
          source:
            description: Defines where is the source of the Helm charts 
            oneOf:
              - $ref: "#/definitions/type_dir"
              - $ref: "#/definitions/type_git"
              - $ref: "#/definitions/type_file"
  required:
    - values
required:
  - schema
  - name
  - chartGroups
  - parallel

definitions:
  type_dir:
    description: The chart source is a directory.
    type: object
    additionalProperties: false
    properties:
      location:
        type: string
    required:
      - type
      - location
  type_file:
    description: The chart source is a file.
    type: object
    properties:
      location:
        type: string
    required:
      - type
      - location
  type_git:
    description: The chart source is a Git repository.
    type: object
    properties:
      location:
        description: URL of the Git repository (the supported protocol format is HTTPS).
        type: string
      subpath:
        description: The subpath to the Chart in the repository.
        type: string
      reference:
        description: Git reference (a branch, a tag, or a release).
        type: string
    required:
      - type
      - location
      - subpath
      - reference
