// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Clusterer is an autogenerated mock type for the Clusterer type
type Clusterer struct {
	mock.Mock
}

// GetKubeConfig provides a mock function with given fields:
func (_m *Clusterer) GetKubeConfig() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetKubeContext provides a mock function with given fields:
func (_m *Clusterer) GetKubeContext() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Init provides a mock function with given fields:
func (_m *Clusterer) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetKubeConfig provides a mock function with given fields: c
func (_m *Clusterer) SetKubeConfig(c string) {
	_m.Called(c)
}

// SetKubeContext provides a mock function with given fields: c
func (_m *Clusterer) SetKubeContext(c string) {
	_m.Called(c)
}
