// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import chartsync "github.com/charter-se/barrelman/manifest/chartsync"
import mock "github.com/stretchr/testify/mock"

// Archiver is an autogenerated mock type for the Archiver type
type Archiver struct {
	mock.Mock
}

// ArchiveRun provides a mock function with given fields: _a0
func (_m *Archiver) ArchiveRun(_a0 *chartsync.ArchiveConfig) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*chartsync.ArchiveConfig) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*chartsync.ArchiveConfig) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPath provides a mock function with given fields:
func (_m *Archiver) GetPath() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
